"""add current_word as optional

Revision ID: 1e399ca0d9da
Revises: 12b1a881f392
Create Date: 2026-04-20 23:51:19.160742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e399ca0d9da'
down_revision: Union[str, Sequence[str], None] = '12b1a881f392'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('games', 'current_word',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('games', 'current_word',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
