"""added turn in GameUser Link table

Revision ID: a9ad30a19763
Revises: b6c94af830e8
Create Date: 2026-05-12 21:23:51.255191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9ad30a19763'
down_revision: Union[str, Sequence[str], None] = 'b6c94af830e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    'game_users',
    sa.Column('turn', sa.Integer(), nullable=False, server_default='0')
    )

    op.add_column(
        'game_users',
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='1')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_users', 'turn')
    # ### end Alembic commands ###
